language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: DKFlXz5l2EkcCZipAsaM1D8y2z/ZmReQp1RItn667LTcUNpyrlmEJiEuL2LT+pKrSTQEMc2rdlpDONM9Vqw1c+MwRFTKwd0ar8BZ0MM70hISWtEKlnHvjd7dSdILp2SAqP+TO49+BRVJa7fx0bL+TbUL3u50omAEvnhzixLLSN7njWlyOfG/1ACgfxaaUurzW68wVHozVkOuY14mzZysh0Ad1lmGeAbcqCDwc6YZ1ASyc0d+OUnpqvczsC/cEeVMPwtkeY9lDpKre3C6I7EZCK3/Ci2RlMMtGcu9HLFROzrojp7kODav7dxDMluuFB0vBSzwbKANrzXgpPFV4ZPjfcJaEzGgPMKKmxFLFLra/18HkvMOSh8/pNz7q30qIPGcXzdcRh1ppgyTgYK4eJzfh77Lvg1GTHZ+94qBZwO602eSRc4gNfV76PxkX4edjP+YKWaukZMn5RcAy9LBFVdbepvVsympN2Y8mCwPOG5kAsebGGLQOiz6+alPA+6AvWG8UqsA2kpNOuOHzB+0BvFb7jG4FReVgpkskIxYPgBKjia1QFZXc7AxHBS8ZhCKKrlp769kx2c6084a2YHz4wAAd5HtA0G9ANyogFnnxuPDiMqIt8ndvzeeTTFN9TiJJfqybDglediYVmFIcxwgJfRX2ROtcjINWiI13A0UkT4bCBw=
  app: quiet-savannah-23779 
  on:
    repo: rposner16/node-capstone
